import { User, Project, Event } from '@/types';

export const MOCK_USER: User = {
    id: 'u1',
    name: 'APSIT Admin',
    email: 'admin@apsit.edu.in',
    role: 'DEPARTMENT',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    bio: 'Official Department Account for APSIT.',
    skills: ['Management', 'Coordination', 'Public Relations'],
    skillTags: ['Management', 'Coordination', 'Public Relations'],
    projectsCount: 12,
    followersCount: 156,
    followingCount: 42,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
};

export const MOCK_STUDENT: User = {
    id: 's1',
    moodleId: '2026001',
    name: 'Zaib Khan',
    email: '2026001@apsit.edu.in',
    role: 'STUDENT',
    branch: 'IT',
    year: 'BE',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80',
    bio: 'Full Stack Developer | AI Enthusiast | APSIT 2026',
    skills: ['Next.js', 'TypeScript', 'Tailwind', 'Python'],
    skillTags: ['Next.js', 'TypeScript', 'Tailwind', 'Python'],
    projectsCount: 5,
    followersCount: 89,
    followingCount: 120,
    githubUsername: 'zaib-khan',
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
};

export const MOCK_DISCOVER_USERS: User[] = [
    {
        id: 's2',
        moodleId: '2026002',
        name: 'Aarav Patil',
        email: '2026002@apsit.edu.in',
        role: 'STUDENT',
        branch: 'IT',
        year: 'TE',
        bio: 'Backend-focused builder who likes APIs, auth, and systems thinking.',
        skills: ['Django', 'Python', 'MySQL', 'JWT'],
        skillTags: ['Django', 'Python', 'MySQL', 'JWT'],
        githubUsername: 'aarav-patil',
        followersCount: 34,
        followingCount: 51,
        projectsCount: 4,
        createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
    },
    {
        id: 's3',
        moodleId: '2026003',
        name: 'Riya Shah',
        email: '2026003@apsit.edu.in',
        role: 'STUDENT',
        branch: 'AI-ML',
        year: 'SE',
        bio: 'Interested in machine learning, NLP, and student-facing products.',
        skills: ['Python', 'TensorFlow', 'NLP', 'Data Science'],
        skillTags: ['Python', 'TensorFlow', 'NLP', 'Data Science'],
        githubUsername: 'riya-shah-ai',
        followersCount: 47,
        followingCount: 38,
        projectsCount: 3,
        createdAt: new Date(Date.now() - 86400000 * 28).toISOString(),
    },
    {
        id: 's4',
        moodleId: '2026004',
        name: 'Kabir Mehta',
        email: '2026004@apsit.edu.in',
        role: 'STUDENT',
        branch: 'CE',
        year: 'BE',
        bio: 'Frontend developer with a thing for polished dashboards and design systems.',
        skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
        skillTags: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
        githubUsername: 'kabir-mehta',
        followersCount: 61,
        followingCount: 74,
        projectsCount: 6,
        createdAt: new Date(Date.now() - 86400000 * 75).toISOString(),
    },
    {
        id: 's5',
        moodleId: '2026005',
        name: 'Neha Kulkarni',
        email: '2026005@apsit.edu.in',
        role: 'STUDENT',
        branch: 'DS',
        year: 'TE',
        bio: 'Data and analytics enthusiast working on campus insights and dashboards.',
        skills: ['Power BI', 'SQL', 'Python', 'Pandas'],
        skillTags: ['Power BI', 'SQL', 'Python', 'Pandas'],
        followersCount: 23,
        followingCount: 29,
        projectsCount: 2,
        createdAt: new Date(Date.now() - 86400000 * 18).toISOString(),
    },
    {
        id: 's6',
        moodleId: '2026006',
        name: 'Ishaan Deshmukh',
        email: '2026006@apsit.edu.in',
        role: 'STUDENT',
        branch: 'IT',
        year: 'SE',
        bio: 'Mobile and IoT tinkerer building prototypes that interact with the physical world.',
        skills: ['Flutter', 'Firebase', 'IoT', 'Arduino'],
        skillTags: ['Flutter', 'Firebase', 'IoT', 'Arduino'],
        followersCount: 18,
        followingCount: 33,
        projectsCount: 3,
        createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    },
    {
        id: 's7',
        moodleId: '2026007',
        name: 'Sara Fernandes',
        email: '2026007@apsit.edu.in',
        role: 'STUDENT',
        branch: 'AI-ML',
        year: 'BE',
        bio: 'Works on recommendation systems, search, and product discovery flows.',
        skills: ['Machine Learning', 'FastAPI', 'Search', 'Recommendation Systems'],
        skillTags: ['Machine Learning', 'FastAPI', 'Search', 'Recommendation Systems'],
        followersCount: 52,
        followingCount: 44,
        projectsCount: 5,
        createdAt: new Date(Date.now() - 86400000 * 54).toISOString(),
    },
];

export const MOCK_DIRECTORY_USERS: User[] = [MOCK_STUDENT, ...MOCK_DISCOVER_USERS];

export const MOCK_TEAMS = [
    {
        id: 't1',
        owner_id: 's1',
        project: 'p1',
        name: 'Sphere Builders',
        description: 'Full stack product team building campus tools, dashboards, and clean user flows.',
        member_count: 3,
        capacity: 5,
        search_keywords: ['full', 'stack', 'product', 'campus', 'tools', 'dashboards', 'user', 'flows'],
        members: [
            { id: 's1', role: 'OWNER' },
            { id: 's2', role: 'MEMBER' },
            { id: 's4', role: 'MEMBER' },
        ],
    },
    {
        id: 't2',
        owner_id: 's3',
        project: 'p3',
        name: 'NLP Circle',
        description: 'AI and NLP team focused on student assistants, semantic search, and recommendation systems.',
        member_count: 3,
        capacity: 5,
        search_keywords: ['ai', 'nlp', 'student', 'assistants', 'semantic', 'search', 'recommendation', 'systems'],
        members: [
            { id: 's3', role: 'OWNER' },
            { id: 's7', role: 'MEMBER' },
            { id: 's5', role: 'MEMBER' },
        ],
    },
    {
        id: 't3',
        owner_id: 's6',
        project: 'p6',
        name: 'IoT Sprint Lab',
        description: 'Prototype team working on mobile, embedded sensors, Firebase sync, and live device telemetry.',
        member_count: 2,
        capacity: 4,
        search_keywords: ['prototype', 'mobile', 'embedded', 'sensors', 'firebase', 'sync', 'device', 'telemetry'],
        members: [
            { id: 's6', role: 'OWNER' },
            { id: 's5', role: 'MEMBER' },
        ],
    },
    {
        id: 't4',
        owner_id: 's2',
        project: 'p2',
        name: 'Mentor Match Ops',
        description: 'Backend and platform team handling matching logic, identity, scheduling, and notifications.',
        member_count: 2,
        capacity: 5,
        search_keywords: ['backend', 'platform', 'matching', 'identity', 'scheduling', 'notifications'],
        members: [
            { id: 's2', role: 'OWNER' },
            { id: 's1', role: 'MEMBER' },
        ],
    },
];

export const MOCK_TEAM_JOIN_REQUESTS = [
    {
        id: 'jr1',
        team_id: 't1',
        team_name: 'Sphere Builders',
        status: 'PENDING',
        message: 'I can help with dashboard polish and responsive layouts.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
        user_id: 's5',
    },
    {
        id: 'jr2',
        team_id: 't4',
        team_name: 'Mentor Match Ops',
        status: 'PENDING',
        message: 'Happy to contribute on auth, APIs, and data flows.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
        user_id: 's4',
    },
];

export const MOCK_PROJECTS: Project[] = [
    {
        id: 'p1',
        title: 'Project Nexus',
        description: 'A comprehensive management system for student collaborations and department events.',
        ownerId: 's1',
        status: 'LOOKING_FOR_TEAMMATES',
        techStack: ['React', 'Node.js', 'MongoDB', 'Tailwind CSS'],
        domainTags: ['Web Development', 'EdTech'],
        teamMemberCount: 3,
        teamCapacity: 5,
        images: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        isBookmarked: false,
    },
    {
        id: 'p2',
        title: 'Campus Mentor Match',
        description: 'A student mentorship platform matching juniors with seniors based on skills and interests.',
        ownerId: 's2',
        status: 'ACTIVE',
        techStack: ['Django', 'React', 'MySQL', 'JWT'],
        domainTags: ['Web Development', 'EdTech'],
        teamMemberCount: 4,
        teamCapacity: 6,
        images: [],
        createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
        updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
        isBookmarked: false,
    },
    {
        id: 'p3',
        title: 'Classroom Query Bot',
        description: 'An NLP assistant for answering common classroom and placement preparation questions.',
        ownerId: 's3',
        status: 'ACTIVE',
        techStack: ['Python', 'TensorFlow', 'NLP', 'FastAPI'],
        domainTags: ['AI/ML', 'EdTech'],
        teamMemberCount: 3,
        teamCapacity: 5,
        images: [],
        createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
        updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
        isBookmarked: false,
    },
    {
        id: 'p4',
        title: 'StudioBoard',
        description: 'A collaborative UI dashboard for managing student clubs, design reviews, and project activity.',
        ownerId: 's4',
        status: 'LOOKING_FOR_TEAMMATES',
        techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Figma'],
        domainTags: ['Web Development', 'Social Platform'],
        teamMemberCount: 2,
        teamCapacity: 5,
        images: [],
        createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
        updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
        isBookmarked: true,
    },
    {
        id: 'p5',
        title: 'APSIT Insight Hub',
        description: 'Analytics workspace for student participation, event attendance, and project trends.',
        ownerId: 's5',
        status: 'ACTIVE',
        techStack: ['Power BI', 'SQL', 'Python', 'Pandas'],
        domainTags: ['Data Science', 'EdTech'],
        teamMemberCount: 3,
        teamCapacity: 4,
        images: [],
        createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
        updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
        isBookmarked: false,
    },
    {
        id: 'p6',
        title: 'EcoTrack Mobile',
        description: 'IoT-enabled mobile application for tracking real-time carbon footprint of campus activities.',
        ownerId: 's6',
        status: 'IN_PROGRESS',
        techStack: ['Flutter', 'Firebase', 'IoT', 'Arduino'],
        domainTags: ['Mobile App', 'IoT/Embedded'],
        teamMemberCount: 4,
        teamCapacity: 4,
        images: [],
        createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
        updatedAt: new Date().toISOString(),
        isBookmarked: true,
    },
    {
        id: 'p7',
        title: 'MatchWise',
        description: 'Recommendation engine for pairing students with projects that fit their skills and goals.',
        ownerId: 's7',
        status: 'ACTIVE',
        techStack: ['FastAPI', 'Python', 'Machine Learning', 'PostgreSQL'],
        domainTags: ['AI/ML', 'Web Development'],
        teamMemberCount: 5,
        teamCapacity: 6,
        images: [],
        createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
        updatedAt: new Date().toISOString(),
        isBookmarked: false,
    },
];

export const MOCK_EVENTS: Event[] = [
    {
        id: 'e1',
        title: 'APSIT Hack-A-Thon 2026',
        description: 'Annual 48-hour hackathon for building innovative solutions for campus life.',
        date: new Date(Date.now() + 86400000 * 10).toISOString(),
        location: 'Main Auditorium, APSIT',
        type: 'HACKATHON',
        thumbnailUrl: '',
        interestedCount: 245,
        isInterested: true,
        isOnline: false,
        createdAt: new Date().toISOString(),
    },
    {
        id: 'e2',
        title: 'Tech Talk: Future of AI',
        description: 'A deep dive into the practical applications of Large Language Models in engineering.',
        date: new Date(Date.now() + 86400000 * 3).toISOString(),
        location: 'Seminar Hall 2',
        type: 'WORKSHOP',
        thumbnailUrl: '',
        interestedCount: 120,
        isInterested: false,
        isOnline: false,
        createdAt: new Date().toISOString(),
    }
];
